### ISSUE TITLE
Chat issue

### ISSUE THREAD

**Issue by shantech82** [shantech82/Upvote#8]
When 2 persons are writing at the same time on the chat and when another send the message then the other one cant continue writing.

Also, we should remove the seconds away from the time messages are sent. Just the hour and minute should be displayed.

**Comment by neatbasis** [comment]
As a user, when I am typing a message into the chat box
and another user sends a message 
The focus should not be stolen from the input box where I'm currently typing a message
when the new message from another user gets rendered to the chat

**Comment by MohanOak** [comment]
I have resolved this issue. Please check.
